# Generated by Django 5.0.1 on 2024-12-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_cloud_url_stock_mse_url_stock_cloud_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationuser',
            old_name='last_update',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='last_update',
            new_name='created_at',
        ),
    ]
