# Generated by Django 5.0.1 on 2024-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_last_update_applicationuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mse_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
